
server:
  port: 8080
logging:
  com.evosome.regit: DEBUG

git-service:
  clone-path: /

repo-providers:
  github:
    apiUrl: https://api.github.com
  bitbucket:
    apiUrl: https://api.bitbucket.org/2.0
